<?php

namespace app\modules\v2\controllers;

use app\models\Ticket;
use app\models\TenantModel;
use Yii;

class TicketsController extends RuraApiController
{
    
    
    public function actionTicket($date, $company)
    {

       if(empty($company) ||  empty($date) /*|| empty($price) || empty($schedule)*/)
                return [['status_code'=>500, 'routes'=>'', 'error'=>'Missing parameter']];

        $tenant = Yii::$app->db->createCommand('SELECT `database` FROM TenantMapping WHERE rura_name  = :tenant')
            ->bindValue(':tenant', $company)
            ->queryScalar();

        if(empty($tenant))
        {
            return [['status_code'=>600, 'routes'=>'', 'error'=>'ticketing system']];
        }
        else
        {
            //Never use sprintf with input that comes from user. $tenant is generated by us and we trust it to be safe and hence the use with sprintf
	    $sql = sprintf("SELECT t.ticket as ticket, t.machine_serial, s.name as updated_by, SUBSTR(t.customer,2,10) as customer,c.name as cname,t.route ,t.start,t.end,t.currency,t.price,t.bus,t.dept_date,t.dept_time,t.updated_at as updated_at FROM %s.Tickets t INNER JOIN %s.Customers c on t.customer= c.mobile INNER JOIN volcano_shared.Staffs s on s.mobile=t.updated_by where t.created_by<>'789238373' AND t.created_by<>'785495363' AND t.dept_time<>'03H00' and  is_promo=0 and rura=1 AND (dept_time<>'23H30' OR dept_time<>'23H00') AND t.bus<>'NONE' AND  t. dept_date=:date order  by t.created_at DESC ", $tenant,$tenant); 
	   $routes =$this->getDb($tenant)->createCommand($sql)
                ->bindValues([
                    ':date' =>$date
		    
                ])
                ->queryAll();
	  
	    $result = [];
            foreach ($routes as $key=>$value) 
	    
            {

	        $agentName = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $value['updated_by']);

		$result["{$key} "]= ['ticket_id' => $value['ticket'], 'pay_method'=>'POS','pos_id'=>$value['machine_serial'],'agent'=>$agentName,'customer_id' => $value['customer'],'customer_full_names'=>$value['cname'],'route_id'=>$value['route'],'route'=>$value['start'].'-'.$value['end'],'company'=> $company,'currency'=>$value['currency'],'price'=>$value['price'],'plate_nbr'=>$value['bus'],'driver_dvc'=>'notset','date'=>$value['dept_date'],'time'=>str_replace('H', ':', $value['dept_time']),'sale_time'=>(new \DateTime())->setTimestamp($value['updated_at'])->format('Y-m-d H:i:s')];
	    }
            
	if (empty($result))
            return [['status_code'=>400, 'tickets'=>'', 'error'=>'ticket not found']];
            

            return ['status_code'=>200, 'tickets'=>$result];   
        }  
  }
}

